CREATE TABLE EMP
(
    ENAME VARCHAR2(20),
    SAL NUMBER(10,2)
);
INSERT ALL
INTO EMP VALUES('ABHISHEK',800)
INTO EMP VALUES('ABHISHEK',0)
INTO EMP VALUES('ABHISHEK',8000)
INTO EMP VALUES('ABHISHEK',8000)
INTO EMP VALUES('ABHISHEK',8000)
INTO EMP VALUES('ABHISHEK',8000)
INTO EMP VALUES('ABHISHEK',8000)
INTO EMP VALUES('ABHISHEK',8000)
SELECT * FROM DUAL;
SELECT * FROM EMP;
SELECT ENAME,SAL
FROM EMP
WHERE SAL>1000;